apiVersion: "serving.kserve.io/v1alpha2"
kind: "InferenceService"
metadata:
  annotations:
    sidecar.istio.io/inject: 'false'
  name: "cat-detect"
spec:
  predictor:
    tensorflow:
      runtimeVersion: 2.5.2
      storageUri: "pvc://workspace-cat-breed-bwxnr12cc/models/tensorflow/"
  minReplicas: 0
